// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.concurrent.TimeUnit;

public class N11SeleniumTest {
    private WebDriver driver;
    private Map<String, Object> vars;
    JavascriptExecutor js;
    int second = 1000;
    @Before
    public void setUp() {
        driver = new ChromeDriver();
        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();
        driver.manage().timeouts().implicitlyWait(3, TimeUnit.SECONDS);
    }

    public void takeTimeot() {
        try {
            Thread.sleep(second);
        } catch (InterruptedException e) {
            e.printStackTrace();
        }
    }
    @After
    public void tearDown() {
        driver.quit();
    }
    @Test
    public void n11v2() {
        driver.manage().timeouts().implicitlyWait(3, TimeUnit.SECONDS);
        driver.get("https://www.n11.com/");
        driver.manage().window().setSize(new Dimension(1920, 1040));
        takeTimeot();
        driver.findElement(By.id("searchData")).click();
        takeTimeot();
        driver.findElement(By.id("searchData")).sendKeys("bilgisayar");
        try {
            Thread.sleep(5000);
        } catch (InterruptedException e) {
            e.printStackTrace();
        }
        driver.findElement(By.cssSelector(".iconsSearch")).click();
        js.executeScript("window.scrollTo(0,113)");
        takeTimeot();
        driver.findElement(By.cssSelector("#p-558847591 .btnBasket")).click();
        takeTimeot();
        driver.findElement(By.id("searchData")).click();
        try {
            Thread.sleep(second);
        } catch (InterruptedException e) {
            e.printStackTrace();
        }
        driver.findElement(By.id("searchData")).click();
        {
            takeTimeot();
            WebElement element = driver.findElement(By.id("searchData"));
            Actions builder = new Actions(driver);
            builder.doubleClick(element).perform();
        }
        takeTimeot();
        driver.findElement(By.id("searchData")).sendKeys("telefon");
        try {
            Thread.sleep(second);
        } catch (InterruptedException e) {
            e.printStackTrace();
        }
        driver.findElement(By.cssSelector(".iconsSearch")).click();
        js.executeScript("window.scrollTo(0,122)");
        {
            takeTimeot();
            WebElement element = driver.findElement(By.cssSelector("#p-533969882 .plink"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element).perform();
        }
        {
            takeTimeot();
            WebElement element = driver.findElement(By.tagName("body"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element, 0, 0).perform();
        }
        takeTimeot();
        driver.findElement(By.cssSelector("#p-508404435 .btnBasket")).click();
        takeTimeot();
        driver.findElement(By.cssSelector("#skus-782319109 > .skus-item:nth-child(1)")).click();
        takeTimeot();
        driver.findElement(By.cssSelector("#skus-782319110 > .skus-item")).click();
        assertThat(driver.findElement(By.cssSelector("#skus-782319109 > .chosen")).getText(), is("Yeşil"));
        assertThat(driver.findElement(By.cssSelector(".seller-name > span")).getText(), is("NITECH"));
        assertThat(driver.findElement(By.id("skus-782319110")).getText(), is("64 GB"));
        takeTimeot();
        driver.findElement(By.id("js-addBasketSku")).click();
        takeTimeot();
        driver.findElement(By.id("searchData")).click();
        takeTimeot();
        driver.findElement(By.id("searchData")).click();

        {
            takeTimeot();
            WebElement element = driver.findElement(By.id("searchData"));
            Actions builder = new Actions(driver);
            builder.doubleClick(element).perform();
        }
        takeTimeot();
        driver.findElement(By.id("searchData")).sendKeys("çikolata");
        try {
            Thread.sleep(second);
        } catch (InterruptedException e) {
            e.printStackTrace();
        }
        driver.findElement(By.cssSelector(".iconsSearch")).click();
        takeTimeot();
        js.executeScript("window.scrollTo(0,133)");
        try {
            Thread.sleep(second);
        } catch (InterruptedException e) {
            e.printStackTrace();
        }
        driver.findElement(By.cssSelector("#p-519776805 .btnBasket")).click();
        takeTimeot();
        driver.findElement(By.cssSelector(".iconsBasketWhite")).click();
        takeTimeot();
        assertThat(driver.findElement(By.cssSelector(".total > .price")).getText(), is("15.541,40 TL"));
        assertThat(driver.findElement(By.cssSelector(".product-total > span:nth-child(1)")).getText(), is("Sipariş Tutarı (3 ürün)"));
    }

}
